language: java

jdk: openjdk11

before_install:
  - openssl aes-256-cbc -K $encrypted_dfb724bdbf52_key -iv $encrypted_dfb724bdbf52_iv -in github_deploy_key.enc -out github_deploy_key -d

script:
  - ./mvnw clean install

deploy:
  provider: script
  skip_cleanup: true
  script: >-
    git checkout master
    ./mvnw --batch-mode release:prepare
  on:
    branch: master
