language: java

jdk: openjdk11

before_install:
  - chmod +x mvnw

script:
- ./mvnw clean install

deploy:
  provider: script
  skip_cleanup: true
  script: ./mvnw --batch-mode release:prepare
  on:
    branch: master
